name: build
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Make Package
        run: |
          make package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spice.unsigned.taco
          path: spice.taco
