name: release
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install Make
        run: |
          brew install make

      - name: Package (unsigned)
        run: |
          make package
          mv spice.taco spice_unsigned.taco

      - name: Upload
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: true
          fail_on_unmatched_files: true
          files: spice_unsigned.taco